steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest', '.']
    id: 'Build the container image'
    waitFor: ["-"]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest']
    id: 'Push the container image to Container Registry'
    waitFor: ["Build the container image"]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'services'
    - 'replace'
    - 'service-monitoring.yaml'
    - '--region'
    - '${_REGION}'
    id: 'Deploy container image to Cloud Run'
    waitFor: ["Push the container image to Container Registry"]

substitutions:
  _SERVICE_NAME: my-service-with-monitoring
  _REGION: europe-west1
